---
apiVersion: v1
kind: Namespace
metadata:
  name: ALM
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ALM
  namespace: ALM
spec:
  selector:
    matchLabels:
      name: ALM
  template:
    metadata:
      labels:
        name: ALM
    spec:
      containers:
      - name: ALM
        image: a4to/ALM:latest
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ALM
  namespace: ALM
spec:
  type: ClusterIP
  selector:
    name: ALM
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP
